# Generated by Django 3.1 on 2020-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Hostel', '0002_hostels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
