# Generated by Django 3.0.2 on 2020-08-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Hostel', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_seller',
            field=models.BinaryField(blank=True, default=False),
        ),
    ]
