# Generated by Django 3.0.2 on 2020-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Hostel', '0006_auto_20200830_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
